version: '3'
services:
  kombi:
    image: kombi
    stdin_open: true
    ports:
      - "80:80"
    networks:
      - kombi-app

  kombi-backend:
    image: kombi-backend
    ports:
      - "4051:4051"
    networks:
      - kombi-app
networks:
  kombi-app:
    driver: bridge