export * from './header/Header'
export * from './footer/footer'
export * from './UI/container/Container'
export * from './UI/slider/Slider'
export * from './page/page'
export * from './catalogCard/CatalogCard'
export * from './catalogOnMainPage/CatalogOnMainPage'
export * from './UI/loader/Loader'